spring.application.name=banque-misr-discovery-server
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
server.port=8761
eureka.client.service-url.defaultZone = http://localhost:8761/eureka/

## Eureka security configurations ##
spring.eureka.security.user.name=bangue.misr.eureka.user
spring.eureka.security.user.password=Bangue#Misr#Challenge#05

## Encrypted eureka password [To login from browser]
## USc6irvCEM8G4dd3QxcE/u0uQiViWuoaAC7Ri5M5QwY9Ui6WdiyPSvTgyZXhR2LvBPeeNvTBjhIm0jFSa/xK7g==

spring.eureka.security.user.role=USER
